# Generated by Django 4.2.1 on 2023-05-30 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_articulo_detarticulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetArticulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('Articulo', models.CharField(max_length=50)),
                ('Observacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='DetArticulo',
        ),
    ]
