# Generated by Django 4.2.1 on 2023-05-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_detarticulo_delete_detarticulos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detarticulo',
            name='Fecha',
            field=models.DateTimeField(),
        ),
    ]
