# Generated by Django 4.2.1 on 2023-06-13 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_articulo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetArticulo',
        ),
    ]
