# Generated by Django 4.2.1 on 2023-06-13 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0008_delete_detarticulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numero', models.CharField(max_length=100)),
                ('Fecha', models.DateTimeField()),
                ('Observacion', models.CharField(max_length=100)),
                ('Cantidad', models.IntegerField()),
                ('Articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.articulo')),
            ],
        ),
    ]
